site_name: InsureOnSim Documentation
nav:
  - Home: index.md
  - API Reference: api.md
  - Classes:
      - World & Zone: classes/World.md
      - Worker: classes/Worker.md
      - Zone States: classes/Zone.md
  - Data Models: models.md
  - Utils: utils.md